FROM python:3.12-slim

WORKDIR /app

# Install dependencies as root before dropping privileges.
# --require-hashes enforces SHA256 verification of every package — pip fails
# the build if any hash mismatches, protecting against supply-chain tampering.
# requirements.txt is generated by: pip-compile --generate-hashes requirements.in
COPY requirements.txt .
RUN pip install --no-cache-dir --require-hashes -r requirements.txt

# Create a non-root user with an explicit UID/GID of 1000.
# Numeric USER below ensures compatibility with Kubernetes runAsNonRoot policies
# and avoids depending on /etc/passwd being present in all base images.
RUN groupadd --gid 1000 appuser && \
    useradd --uid 1000 --gid 1000 --no-create-home --shell /bin/false appuser

# Copy application files and set ownership in a single layer.
# --chown avoids a separate RUN chown that would double the layer size for /app.
COPY --chown=1000:1000 . .

USER 1000

ENV PYTHONUNBUFFERED=1

EXPOSE 5000

CMD ["gunicorn", "-c", "gunicorn.conf.py", "main:app"]
