# Stage 1: Build the React frontend
FROM node:20-alpine AS frontend
WORKDIR /ui
COPY ui/package.json ui/package-lock.json ./
RUN npm ci --ignore-scripts
COPY ui/ ./
RUN npm run build

# Stage 2: Python application
FROM python:3.12-slim

WORKDIR /app

# Install dependencies as root before dropping privileges.
# --require-hashes enforces SHA256 verification of every package — pip fails
# the build if any hash mismatches, protecting against supply-chain tampering.
# requirements.txt is generated by: pip-compile --generate-hashes requirements.in
COPY requirements.txt .
RUN pip install --no-cache-dir --require-hashes -r requirements.txt

# Create a non-root user with an explicit UID/GID of 1000.
# Numeric USER below ensures compatibility with Kubernetes runAsNonRoot policies
# and avoids depending on /etc/passwd being present in all base images.
RUN groupadd --gid 1000 appuser && \
    useradd --uid 1000 --gid 1000 --create-home --shell /bin/false appuser

# Create the data directory for the SQLite alert log and runbooks/topology.
# Named volume mounts copy the image directory's ownership — setting it here
# ensures the volume is initialised with the correct UID before USER drops root.
RUN mkdir -p /data/runbooks && chown -R 1000:1000 /data

# Copy application files and set ownership in a single layer.
# --chown avoids a separate RUN chown that would double the layer size for /app.
COPY --chown=1000:1000 . .

# Copy built frontend from stage 1 into the static directory.
# Vite builds into /static (ui/../static from workdir /ui).
# Flask serves these via the SPA-aware 404 handler.
COPY --from=frontend --chown=1000:1000 /static /app/static

USER 1000

ENV PYTHONUNBUFFERED=1

EXPOSE 5000

CMD ["gunicorn", "-c", "gunicorn.conf.py", "main:app"]
